In [9]:
pwd

'/mnt/i/work_dirs'

In [2]:
#pip install numpy

  Using cached numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pickle
from pickle import load
import numpy
#from numpy import range

In [11]:
test_data = load(open('result_t2_scratch.pkl', 'rb'))

In [14]:
len(test_data)

473

In [15]:
test_data

[array([1.8683056e-04, 1.8608245e-05, 1.9233680e-03, 1.9528704e-03,
        3.2216836e-02, 1.7841370e-01, 9.0207309e-02, 3.8777385e-02,
        6.5156311e-01, 6.7713903e-04, 6.7714171e-04, 6.7713659e-04,
        6.7713414e-04, 6.7713542e-04, 6.7714055e-04, 6.7714119e-04],
       dtype=float32),
 array([2.6924434e-05, 3.9631550e-07, 1.1011822e-03, 4.0025422e-03,
        1.2896940e-04, 4.0430706e-02, 5.2488154e-01, 1.5869778e-02,
        4.1247115e-01, 1.5526419e-04, 1.5526504e-04, 1.5526528e-04,
        1.5526322e-04, 1.5526517e-04, 1.5526438e-04, 1.5526488e-04],
       dtype=float32),
 array([2.0985898e-04, 2.3497194e-05, 6.2584686e-03, 8.0928713e-04,
        3.4332834e-03, 4.7389433e-01, 6.8891637e-02, 1.2822013e-01,
        3.1415108e-01, 5.8692921e-04, 5.8693200e-04, 5.8693008e-04,
        5.8692839e-04, 5.8692944e-04, 5.8693276e-04, 5.8692944e-04],
       dtype=float32),
 array([1.5629686e-05, 7.0193607e-08, 5.6057859e-05, 1.5667925e-04,
        1.4487791e-02, 3.3348069e-02, 1.4221

In [16]:
test_data[0]

array([1.8683056e-04, 1.8608245e-05, 1.9233680e-03, 1.9528704e-03,
       3.2216836e-02, 1.7841370e-01, 9.0207309e-02, 3.8777385e-02,
       6.5156311e-01, 6.7713903e-04, 6.7714171e-04, 6.7713659e-04,
       6.7713414e-04, 6.7713542e-04, 6.7714055e-04, 6.7714119e-04],
      dtype=float32)

In [17]:
test_data[472]

array([0.34247467, 0.03166059, 0.16562419, 0.02565314, 0.03022617,
       0.00519611, 0.15554103, 0.18549338, 0.02036168, 0.00539562,
       0.00539556, 0.00539559, 0.00539557, 0.00539557, 0.00539558,
       0.00539558], dtype=float32)

In [19]:
with open('../pth/figure_normal/validation_normal_dop_t2.pkl', 'rb') as f:
    answer = pickle.load(f)

In [20]:
len(answer)

473

In [23]:
len(answer[0])

7

In [ ]:
import pickle
import numpy as np
from sklearn.metrics import top_k_accuracy_score
with open('result_figure_full_last.pkl', 'rb') as f:
    data = pickle.load(f)
with open('./data/figure_full/test_full.pkl', 'rb') as f:
    answer = pickle.load(f)
answer = np.array([int(ans['label']) for ans in answer])

top_3 = top_k_accuracy_score(answer, data, k=3, labels=np.arange(53))
print('Top-3 Accuracy: ', round(top_3*100, 2), '%')